#!/usr/bin/env bash

(
    cd "$( dirname $( dirname "${BASH_SOURCE[0]}" ) )"
    git_root="$(git rev-parse --show-toplevel)"
    cd $git_root

    branch="$(git rev-parse --abbrev-ref HEAD)"
    if [ $branch != "development" ]
    then
        echo "❌ Branch is not master; instead, was '$branch'."
        exit 1
    fi
    echo "✅ Branch is '$branch'!"

    diffWithOrigin=$(git diff --name-only origin/development)
    if [[ $diffWithOrigin != "" ]]
    then
        echo "❌ Local master branch must be in sync with origin/master.";
        exit 1;
    fi
)