#!/usr/bin/env bash

# branch="$(git rev-parse --abbrev-ref HEAD)"
# if [ $branch != "development" ]
# then
#     echo "❌ Branch is not development; instead, was '$branch'."
#     exit -1
# fi
# echo "✅ Branch is '$branch'!"

git diff-index --quiet HEAD --
if [ $? -eq 1 ]
then
    echo "❌ Branch has unstaged or uncommitted changes."
    exit -1
fi
echo "✅ No uncommitted changes!"